version: '3.4'

services:

    router:
        image: binocarlos/noxy
        ports:
            - 80:80
        container_name: router
        environment:
            - NOXY_DEFAULT_HOST=ui-prod
            - NOXY_DEFAULT_PORT=3030
            - NOXY_DEFAULT_WS=1
            - NOXY_API_FRONT=/api
            - NOXY_API_HOST=server-prod
            - NOXY_API_PORT=9000
        networks:
            - paulwizviz_react_training_network

    ui-prod:
        image: ${UI_IMAGE_PROD}:${IMAGE_TAG}
        container_name: ui-prod
        expose:
            - 3030
        ports:
            - 3030:3030
        working_dir: /opt
        command: ["npm", "start"]
        networks:
            - paulwizviz_react_training_network

    server-prod:
        image: ${SERVER_IMAGE}:${IMAGE_TAG}
        container_name: server-prod
        expose:
            - 9000
        ports:
            - 9000:9000
        volumes: 
            - ../server/src:/opt/src
        networks:
            - paulwizviz_react_training_network

networks:
    paulwizviz_react_training_network:
