version: '3.4'

services:

    router:
        image: binocarlos/noxy
        ports:
            - 80:80
        container_name: router
        environment:
            - NOXY_DEFAULT_HOST=ui-dev
            - NOXY_DEFAULT_PORT=3031
            - NOXY_DEFAULT_WS=1
            - NOXY_API_FRONT=/api
            - NOXY_API_HOST=server-dev
            - NOXY_API_PORT=9000
        networks:
            - paulwizviz_react_training_network

    ui:
        image: node:13.10.1
        container_name: ui-dev
        expose:
            - 3031
        ports:
            - 3031:3031
        volumes:
            - ../ui/images:/opt/images
            - ../ui/src:/opt/src
            - ../ui/webpack:/opt/webpack
            - ../ui/.babelrc:/opt/.babelrc
            - ../ui/.eslintrc.json:/opt/.eslintrc.json
            - ../ui/package-lock.json:/opt/package-lock.json
            - ../ui/package.json:/opt/package.json
        working_dir: /opt
        command: ["npm", "run", "dev"]
        networks:
            - paulwizviz_react_training_network

    server:
        build:
            context: ../
            dockerfile: ./build/server.dockerfile
        image: ${SERVER_IMAGE}:${IMAGE_TAG}
        container_name: server-dev
        expose:
            - 9000
        ports:
            - 9000:9000
        volumes: 
            - ../server/src:/opt/src
        networks:
            - paulwizviz_react_training_network

networks:
    paulwizviz_react_training_network:
