version: '3.4'

services:

    # router:
    #     image: binocarlos/noxy
    #     ports:
    #         - 80:80
    #     container_name: router
    #     environment:
    #         - NOXY_DEFAULT_HOST=reactjs
    #         - NOXY_DEFAULT_PORT=3030
    #         - NOXY_DEFAULT_WS=1
    #         - NOXY_API_FRONT=/api
    #         - NOXY_API_HOST=express
    #         - NOXY_API_PORT=9000
    #     networks:
    #         - local

    reactjs:
        image: $REACTJS_IMAGE
        container_name: reactjs
        expose:
            - 3030
        ports:
            - 3030:3030
        working_dir: /opt
        command: ["npm", "run", "dev"]
        networks:
            - local

    express:
        image: ${EXPRESS_IMAGE}
        container_name: express
        expose:
            - 9000
        ports:
            - 9000:9000
        networks:
            - local

networks:
    local:
        name: ${NETWORK_NAME}
